### ISSUE TITLE
fix(client-python): package declares requires-python >=3.10 but imports typing.NotRequired (3.11+), so import rocketride fails

### ISSUE THREAD

**Issue by Aryan-070** [rocketride-org/rocketride-server#1820]
### Description

`packages/client-python/pyproject.toml:45` declares `requires-python = ">=3.10"` and ships the `Programming Language :: Python :: 3.10` trove classifier (`:23`). But `packages/client-python/src/rocketride/types/billing.py:39` does:

```python
from typing import Literal, NotRequired, TypedDict
```

`typing.NotRequired` was added in **Python 3.11** (PEP 655). On 3.10 it does not exist, so `import rocketride` fails outright.

The import is unconditional and on the main import path — not guarded by `TYPE_CHECKING` — and `types/__init__.py:190` does `from .billing import (...)` unconditionally. So this is total failure to import, not a partial degradation.

This is live on PyPI: `rocketride` **1.3.0** publishes `requires_python: ">=3.10"`, carries the 3.10 classifier, and lists no `typing_extensions` in `requires_dist`. A 3.10 user gets a clean `pip install` and an immediate `ImportError`.

**The 3.10 floor looks deliberate, not accidental**, which is why the fix is a compatibility shim rather than raising the floor:

- #434 → PR #491 moved it from `>=3.8` to `>=3.10` on purpose
- the root `pyproject.toml` sets ruff `target-version = "py310"`
- `scripts/compiler-unix.sh` hard-fails below 3.10 while advertising "Ubuntu 22.04 or newer (has Python 3.10+)" as supported

That is a configuration on which `import rocketride` raises.

**Scope is exactly one file.** A sweep of `packages/client-python/src/` for other 3.11+/3.12+ constructs (`Required`, `Self`, `LiteralString`, `TypeVarTuple`, `Unpack`, `assert_never`, `override`) found no other offender. `billing.py` holds all 17 `NotRequired` uses (`:39`, `:101`, `:131`, and the `:216-228` / `:247` blocks).

### Steps to Reproduce

Verified on CPython **3.10.6**, against the current `origin/develop` source:

```bash
python3.10 -c "from typing import NotRequired"
# ImportError: cannot import name 'NotRequired' from 'typing'
```

End-to-end, importing the shipped package:

```bash
git archive origin/develop packages/client-python/src | tar -x -C /tmp/rr
python3.10 -c "import sys; sys.path.insert(0,'/tmp/rr/packages/client-python/src'); import rocketride"
# ImportError: cannot import name 'NotRequired' from 'typing'
```

And from PyPI:

```bash
python3.10 -m venv /tmp/rr310
/tmp/rr310/bin/pip install rocketride     # succeeds — metadata says >=3.10
/tmp/rr310/bin/python -c "import rocketride"
```

### Expected vs Actual Behavior

**Expected** — either `import rocketride` works on 3.10, or the package refuses to install there.

**Actual** — installation succeeds and import fails:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../rocketride/__init__.py", line 90, in <module>
  File ".../rocketride/types/__init__.py", line 190, in <module>
  File ".../rocketride/types/billing.py", line 39, in <module>
    from typing import Literal, NotRequired, TypedDict
ImportError: cannot import name 'NotRequired' from 'typing'
```

### Severity

P1 - High (major feature broken, no workaround)

The package cannot be imported at all on a version it declares support for, and the affected release is public.

### Platform

Windows, macOS, Linux

Interpreter-version dependent, not OS dependent.

### Version / Environment

`rocketride` 1.3.0 (PyPI) and `origin/develop` @ `243c1f26`; reproduced on CPython 3.10.6, macOS.

### Screenshots / Logs

**Suggested fix** — `typing_extensions` re-exports `NotRequired` for 3.10:

```python
from typing import Literal, TypedDict
from typing_extensions import NotRequired
```

plus `typing_extensions` added to `dependencies` in `packages/client-python/pyproject.toml`. It is currently present only *transitively* — `pydantic>=2.0.0` requires it (`pip show pydantic` → `Requires: annotated-types, pydantic-core, typing-extensions`) — so it resolves today but is not something this package declares or controls. Verified `from typing_extensions import NotRequired` works on 3.10.6.

**Why CI did not catch it.** The only `python-version:` pins across the workflows are `'3.12'`; there is no version matrix. The client-python tests run under the engine's *embedded* interpreter (`packages/client-python/scripts/tasks.js` → `scripts/lib/pytest.js` → `dist/server/engine -m pytest`), never the runner's Python. The only PR-level Python gate is `ruff check`, whose selected rules (`E,F,Q,D`) cannot flag a version-incompatible stdlib import.

A secondary ask worth considering separately: exercise the SDK once on its declared minimum in CI, so the floor is a tested claim rather than a documented one. Related: #434, which set the 3.10 floor in the first place.
